version : '3'

services:

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

volumes:
  app-usr-local-bin:
    driver: local

  mongo-data:
    driver: local